export const SERVICES = [
  {
    id: 1,
    name: "Bơi lội",
    category: "Thể thao",
    icon: "water-outline",
    onPress: (navigation: any) => navigation.navigate("swimming" as never),
  },
  {
    id: 2,
    name: "Bãi đậu xe",
    category: "Giao thông",
    icon: "car-outline",
    onPress: () => console.log("Bãi đậu xe được chọn"),
  },
  {
    id: 3,
    name: "Phòng gym",
    category: "Thể thao",
    icon: "barbell-outline",
    onPress: () => console.log("Phòng gym được chọn"),
  },
  {
    id: 4,
    name: "Điện nước",
    category: "Tiện ích",
    icon: "flash-outline",
    // onPress: () => console.log("Điện nước được chọn"),
  },
  {
    id: 5,
    name: "Quản lý cư dân",
    category: "Cư dân",
    icon: "people-outline",
    onPress: () => console.log("Quản lý cư dân được chọn"),
  },
  {
    id: 6,
    name: "Phí dịch vụ",
    category: "Tài chính",
    icon: "wallet-outline",
    onPress: () => console.log("Phí dịch vụ được chọn"),
  },
  {
    id: 7,
    name: "Bảo trì & Sửa chữa",
    category: "Hạ tầng",
    icon: "build-outline",
    onPress: () => console.log("Bảo trì & Sửa chữa được chọn"),
  },
  {
    id: 8,
    name: "An ninh & Giám sát",
    category: "An ninh",
    icon: "shield-checkmark-outline",
    onPress: () => console.log("An ninh & Giám sát được chọn"),
  },
  {
    id: 9,
    name: "Quản lý đặt chỗ",
    category: "Tiện ích",
    icon: "calendar-outline",
    onPress: () => console.log("Quản lý đặt chỗ được chọn"),
  },
] as const;
